package com.example.mybatisxmldemo.mapper;

import com.example.mybatisxmldemo.model.Message4;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MessageMapper4 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    long countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    @Delete({
            "delete from message",
            "where msg_id = #{msgId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    @Insert({
            "insert into message (msg_id, msg_text, ",
            "msg_summary)",
            "values (#{msgId,jdbcType=INTEGER}, #{msgText,jdbcType=VARCHAR}, ",
            "#{msgSummary,jdbcType=VARCHAR})"
    })
    int insert(Message4 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    int insertSelective(Message4 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    List<Message4> selectByExampleWithRowbounds(MessageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    List<Message4> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "msg_id, msg_text, msg_summary",
            "from message",
            "where msg_id = #{msgId,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.mybatisgeneratordemo.mapper.MessageMapper.BaseResultMap")
    Message4 selectByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Message4 record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Message4 record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Message4 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    @Update({
            "update message",
            "set msg_text = #{msgText,jdbcType=VARCHAR},",
            "msg_summary = #{msgSummary,jdbcType=VARCHAR}",
            "where msg_id = #{msgId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Message4 record);
}
